name: PYCOURSE
channels:
  - conda-forge
dependencies:
  - python=3.8
  - altair
  - cartopy
  - cdsapi
  - ciso
  - erddapy
  - folium
  - gcsfs
  - geopandas
  - git
  - gsw
  - holoviews
  - hvplot
  - intake
  - intake-esm
  - ioos_qc
  - iris
  - jupyter
  - jupyter_contrib_nbextensions
  - matplotlib-base
  - netcdf4
  - numpy
  - oceans
  - palettable
  - pandas
  - proplot
  - rise
  - scikit-learn
  - scipy
  - seaborn
  - statsmodels
  - utide
  - windrose
  - xarray
  - xlrd
  - zarr
  # R packages.
  - rpy2
  - r-base=3.6
  - r-dt
  - r-finch
  - r-ggfortify
  - r-ggplot2
  - r-gsw
  - r-httr
  - r-irkernel
  - r-lubridate
  - r-mapdata
  - r-ncdf4
  - r-oce
  - r-rcolorbrewer
  - r-rerddap
  - r-reshape2
  - r-robis
  - r-sp
  - r-xtractomatic
  - r-xts
