name: PYCOURSE
channels:
  - conda-forge
dependencies:
  - python=3.9
  - cartopy
  - erddapy
  - folium
  - geopandas
  - gsw
  - jupyter
  - jupyter_contrib_nbextensions
  - matplotlib-base
  - netcdf4
  - numpy
  - oceans
  - openpyxl
  - palettable
  - pandas
  - scipy
  - seaborn
  - shapely
  - xarray
