name: Windows

on:
  pull_request:
  push:
    branches: [main]

jobs:
  run:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Conda
      uses: s-weigand/setup-conda@v1
      with:
        activate-conda: false
        conda-channels: conda-forge

    - name: Create the environment
      shell: bash -l {0}
      run: |
        conda env create --file environment.yml --name TEST
        conda install --name TEST --channel conda-forge nbval pytest
        source activate TEST

    - name: Tests
      shell: bash -l {0}
      run: |
        source activate TEST
        pytest --nbval-lax -p no:python .
